services:
  sas_core:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    command: /bin/bash -c "bash /root/sas_core_devel/src/sas_core/docker/smoke_test.sh"
